[project]
name = "clarity-experiments"
authors = []
description = ""
telemetry = false
requirements = []
costs_version = 1
[contracts.custom-iteration]
path = "contracts/custom-iteration.clar"
depends_on = []

[contracts.double-linked-list]
path = "contracts/double-linked-list.clar"
depends_on = []

[contracts.items-storage]
path = "contracts/proxy/items-storage.clar"
depends_on = []

[contracts.proxy-v1]
path = "contracts/proxy/proxy-v1.clar"
depends_on = ["items-storage"]

[contracts.proxy-v2]
path = "contracts/proxy/proxy-v2.clar"
depends_on = ["items-storage"]

[contracts.todos]
path = "contracts/todos.clar"
depends_on = []
