[project]
name = "clarity-experiments"
authors = []
description = ""
telemetry = false
requirements = []
costs_version = 1
[contracts.custom-iteration]
path = "contracts/custom-iteration.clar"
depends_on = []

[contracts.double-linked-list]
path = "contracts/double-linked-list.clar"
depends_on = []

[contracts.hex-color]
path = "contracts/hex-color.clar"
depends_on = []

[contracts.items-storage]
path = "contracts/proxy/items-storage.clar"
depends_on = []

[contracts.proxy-v1]
path = "contracts/proxy/proxy-v1.clar"
depends_on = ["items-storage"]

[contracts.proxy-v2]
path = "contracts/proxy/proxy-v2.clar"
depends_on = ["items-storage"]

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []

[contracts.svg-nft]
path = "contracts/svg-nft.clar"
depends_on = ["sip009-nft-trait"]

[contracts.todos]
path = "contracts/todos.clar"
depends_on = []

[contracts.var-get-costs]
path = "contracts/costs-analysis/var-get-costs.clar"
depends_on = []

[contracts.is-sorted]
path = "contracts/costs-analysis/is-sorted.clar"
depends_on = []

[contracts.sender-test-a]
path = "contracts/tx-sender-test/sender-test-a.clar"
depends_on = []

[contracts.sender-test-b]
path = "contracts/tx-sender-test/sender-test-b.clar"
depends_on = []
